defaults:
  - _self_

# General settings
seed: 42

# DataModule settings
data:
  data_dir: "../../../data/processed"
  batch_size: 32
  num_workers: 4
  image_size: [256, 256]

# Model settings
model:
  name: "resnet50"  # Options: 'resnet50', 'resnet101'
  num_classes: 6
  learning_rate: 2e-5
  scheduler:
    step_size: 7
    gamma: 0.1

# Trainer settings
trainer:
  max_epochs: 20
  precision: 16  # 32 for full precision, 16 for mixed precision
  callbacks:
    checkpoint:
      monitor: "val_f1"
      dirpath: "models/"
      filename: "car_damage-{epoch:02d}-{val_acc:.4f}"
      save_top_k: 1
      mode: "max"

# WandB settings
logger:
  wandb:
    project: "car-damage-classification"
    entity: null  # Replace with your W&B entity/team name if applicable
    log_model: False

# Logging settings
logging:
  version: 1
  disable_existing_loggers: false
